version: '2'
services:
  video-h264-decoder:
    build:
      context: https://github.com/chalmers-revere/opendlv-video-h264-replay.git#v0.0.4
      dockerfile: Dockerfile
    restart: on-failure
    network_mode: "host"
    ipc: "host"
    volumes:
      - /tmp:/tmp
      - ./Videos:/videos
    environment:
      - DISPLAY=${DISPLAY}
    command: "--cid=253 --name=img /videos/video${VID_NR}.rec"
    healthcheck:
      test: ls || exit 1
      interval: 5s
      start_period: 5s

  group14:
    depends_on:
      video-h264-decoder:
          condition: service_healthy 
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    ipc: "host"
    volumes:
      - /tmp:/tmp
      - ./Generated_CSV:/Generated_CSV
    environment:
      - DISPLAY=${DISPLAY}
    command: "--cid=253 --name=img --width=640 --height=480 ${VID_NR}"