version: '2'
services:
    rec2csv_png:
        build:
            context: https://github.com/chalmers-revere/rec2csv-png.git
            dockerfile: Dockerfile
        restart: on-failure
        volumes:
        - .:/opt/data
        working_dir: /opt/data
        command: "--rec=Videos/video${CURRENT_VIDEO}.rec --odvd=opendlv-standard-message-set-v0.9.9.odvd"